groups:
  - key: PROXY
    type: select
    members:
      - "@FALLBACK"
      - "@AUTO"
      - "@MANUAL"
      - DIRECT
    include_nodes: all
  - key: FALLBACK
    type: fallback
    include_nodes: true
    url: https://www.gstatic.com/generate_204
    interval: 300
    timeout: 3000
  - key: AUTO
    type: url-test
    include_nodes: true
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    timeout: 3000
  - key: MANUAL
    type: select
    include_nodes: all
  - key: RuleUpdate
    type: select
    members:
      - "@PROXY"
      - "@FALLBACK"
      - DIRECT
  - key: GitHub
    type: select
    members:
      - "@PROXY"
      - "@FALLBACK"
      - "@AUTO"
      - "@MANUAL"
    include_nodes: true
  - key: AI_FALLBACK
    type: fallback
    include_nodes:
      source_ids:
        - mesl
      name_contains:
        - 家宽
      preferred_name_contains:
        - 台湾 09 家宽
        - 台湾 08 家宽
      fallback_include_nodes: true
    url: https://chatgpt.com/cdn-cgi/trace
    interval: 300
    timeout: 5000
  - key: AI_AUTO
    type: url-test
    include_nodes:
      source_ids:
        - mesl
      name_contains:
        - 家宽
      preferred_name_contains:
        - 台湾 09 家宽
        - 台湾 08 家宽
      fallback_include_nodes: true
    url: https://chatgpt.com/cdn-cgi/trace
    interval: 300
    tolerance: 50
    timeout: 5000
  - key: AI
    type: select
    members:
      - "@AI_FALLBACK"
      - "@AI_AUTO"
      - "@MANUAL"
  - key: Google
    type: select
    members:
      - "@PROXY"
      - "@FALLBACK"
      - "@AUTO"
      - "@MANUAL"
    include_nodes: true
  - key: Developer
    type: select
    members:
      - "@PROXY"
      - "@FALLBACK"
      - "@AUTO"
      - "@MANUAL"
    include_nodes: true
  - key: Apple
    type: select
    members:
      - DIRECT
      - "@PROXY"
      - "@FALLBACK"
      - "@AUTO"
    include_nodes: true
  - key: Microsoft
    type: select
    members:
      - "@PROXY"
      - "@FALLBACK"
      - DIRECT
      - "@AUTO"
    include_nodes: true
  - key: Telegram
    type: select
    members:
      - "@PROXY"
      - "@FALLBACK"
      - "@AUTO"
      - "@MANUAL"
    include_nodes: true
  - key: Streaming
    type: select
    members:
      - "@PROXY"
      - "@FALLBACK"
      - "@AUTO"
      - "@MANUAL"
    include_nodes: true
  - key: Download
    type: select
    members:
      - "@FALLBACK"
      - "@PROXY"
      - "@AUTO"
      - "@MANUAL"
    include_nodes: true
  - key: Final
    type: select
    members:
      - "@PROXY"
      - "@FALLBACK"
      - "@AUTO"
      - DIRECT
    include_nodes: true
