last_rule_prefix: MATCH,
ipv6_disabled: true
foreign_groups_no_direct_first:
  - PROXY
  - Final
  - GitHub
  - AI
  - Google
  - Developer
  - Microsoft
  - Telegram
  - Streaming
  - Download
  - RuleUpdate
foreign_groups_no_direct_member:
  - GitHub
  - Developer
  - Streaming
  - Download
rule_order:
  - before: DOMAIN-SUFFIX,github.com
    after: RULE-SET,download_domainset
  - before: GEOSITE,github
    after: RULE-SET,download_domainset
  - before: RULE-SET,ai
    after: RULE-SET,download_domainset
  - before: RULE-SET,apple_intelligence
    after: RULE-SET,download_domainset
  - before: GEOSITE,google
    after: RULE-SET,download_domainset
  - before: RULE-SET,developer_global
    after: RULE-SET,download_domainset
  - before: DOMAIN-SUFFIX,npmmirror.com
    after: RULE-SET,developer_global
  - before: DOMAIN-SUFFIX,goproxy.cn
    after: RULE-SET,developer_global
  - before: RULE-SET,microsoft
    after: RULE-SET,download_domainset
  - before: RULE-SET,microsoft_cdn
    after: RULE-SET,download_domainset
  - before: RULE-SET,apple_cdn
    after: RULE-SET,download_domainset
  - before: GEOSITE,cn
    after: AND,((RULE-SET,download_domainset),(GEOIP,CN)),DIRECT
  - before: AND,((RULE-SET,download_domainset),(GEOIP,CN)),DIRECT
    after: RULE-SET,download_domainset
  - before: AND,((RULE-SET,download_non_ip),(GEOIP,CN)),DIRECT
    after: RULE-SET,download_non_ip
  - before: RULE-SET,download_domainset
    after: GEOIP,CN
  - before: GEOSITE,geolocation-!cn
    after: GEOIP,CN
required_rules:
  - DOMAIN-SUFFIX,github.com
  - DOMAIN-SUFFIX,objects.githubusercontent.com
  - DOMAIN-SUFFIX,release-assets.githubusercontent.com
  - DOMAIN-SUFFIX,github-releases.githubusercontent.com
  - DOMAIN-SUFFIX,chatgpt.com
  - DOMAIN-SUFFIX,claude.ai
  - RULE-SET,apple_intelligence
  - RULE-SET,direct_non_ip
  - RULE-SET,global_non_ip
  - RULE-SET,developer_global
  - AND,((RULE-SET,download_domainset),(GEOIP,CN)),DIRECT
  - AND,((RULE-SET,download_non_ip),(GEOIP,CN)),DIRECT
  - GEOSITE,github
  - GEOSITE,google
  - GEOIP,CN
  - MATCH,
